#!/bin/sh

die() {
  printf "mount: %s\n" "$*" >&2
  exit 1
}

if ! command -v aft-mtp-mount > /dev/null; then
  die "android-file-transfer-linux not installed"
fi

if [ -e /tmp/android ]; then
  die "directory '/tmp/android': already exists"
fi

install -d -m 700 /tmp/android

if ! aft-mtp-mount /tmp/android; then
  rmdir /tmp/android

  die "failed to mount device"
fi

exec thunar /tmp/android

# fusermount -u /tmp/android
